// Datos de piezas y baremos — Estudio Patitucci (extraído de index.html, Tarea 18)
// Expone window.CALC_DATA_GRID. Cargar ANTES del script principal.
(function(){
var _p=function(n,r,hs,panos,hsR,sub){return {nombre:n,requierePintura:!!r,defaultHs:hs||0,defaultPanos:panos||0,defaultHsR:hsR||0,sub:sub||''};};
var S=true,N=false;
var _Z9_SEG=[
  _p('Airbag conductor',N,1),_p('Airbag acompañante',N,1),
  _p('Plancha abordo',N,4),
  _p('Airbag rodilla conductor',N,1),
  _p('Airbag de butaca conductor',N,2),_p('Airbag de butaca acompañante',N,2),
  _p('Airbag cortina lateral izquierdo',N,2),_p('Airbag cortina lateral derecho',N,2),
  _p('Cinturón / pretensor conductor',N,1),
  _p('Cinturón / pretensor acompañante',N,1),_p('Módulo airbag / pretensores',N,1)
];
var _B1_Z1=[
  _p('Paragolpes delantero',S,8,1.5,0,'Paragolpes delantero'),
  _p('Alma metálica de paragolpes delantero',S,8,1,0,'Paragolpes delantero'),
  _p('Absorbedor de impacto interno de paragolpes',N,0,0,0,'Paragolpes delantero'),
  _p('Soporte de paragolpes delantero izquierdo',N,0,0,0,'Paragolpes delantero'),
  _p('Soporte de paragolpes delantero derecho',N,0,0,0,'Paragolpes delantero'),
  _p('Guía lateral de paragolpes delantero izquierda',N,0,0,0,'Paragolpes delantero'),
  _p('Guía lateral de paragolpes delantero derecha',N,0,0,0,'Paragolpes delantero'),
  _p('Rejilla frontal superior (Central)',N,0,0,0,'Paragolpes delantero'),
  _p('Rejilla frontal inferior (Central)',N,0,0,0,'Paragolpes delantero'),
  _p('Marco de faro auxiliar izquierdo',N,0,0,0,'Paragolpes delantero'),
  _p('Marco de faro auxiliar derecho',N,0,0,0,'Paragolpes delantero'),
  _p('Faro auxiliar izquierdo (Antiniebla)',N,0,0,0,'Paragolpes delantero'),
  _p('Faro auxiliar derecho (Antiniebla)',N,0,0,0,'Paragolpes delantero'),
  _p('Embellecedor de paragolpes delantero izquierdo',N,0,0,0,'Paragolpes delantero'),
  _p('Embellecedor de paragolpes delantero derecho',N,0,0,0,'Paragolpes delantero'),
  _p('Spoiler inferior de paragolpes delantero',N,0,0,0,'Paragolpes delantero'),
  _p('Deflector de aire inferior de paragolpes delantero',N,0,0,0,'Paragolpes delantero'),
  _p('Capot',S,3,3,0,'Capot'),
  _p('Manta aislante de capot (Insonorizador)',N,0,0,0,'Capot'),
  _p('Burlete de capot',N,0,0,0,'Capot'),
  _p('Bisagra de capot izquierda',S,0,0,0,'Capot'),
  _p('Bisagra de capot derecha',S,0,0,0,'Capot'),
  _p('Cerradura de capot',N,0,0,0,'Capot'),
  _p('Traba de seguridad de capot',N,0,0,0,'Capot'),
  _p('Guardabarros delantero izquierdo',S,4,1,0,'GDI + Óptica I + G.Plast I'),
  _p('Óptica principal izquierda',N,0,0,0,'GDI + Óptica I + G.Plast I'),
  _p('Guardaplast izquierdo',N,0,0,0,'GDI + Óptica I + G.Plast I'),
  _p('Guardabarros delantero derecho',S,4,1,0,'GDD + Óptica D + G.Plast D'),
  _p('Óptica principal derecha',N,0,0,0,'GDD + Óptica D + G.Plast D'),
  _p('Guardaplast derecho',N,0,0,0,'GDD + Óptica D + G.Plast D'),
  _p('Máscara plástica',N,0,0,0,'Frente de carrocería'),
  _p('Travesaño superior de panel frontal',S,2,0.5,0,'Frente de carrocería'),
  _p('Travesaño inferior de panel frontal',S,2,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero izquierdo',S,16,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero derecho',S,16,0.5,0,'Frente de carrocería')
];
var _B1_Z2=[
  _p('Puerta delantera izquierda',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda superior',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda inferior',S,0,0,0,'Puerta delantera'),
  _p('Limitador de apertura de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Coliza barrevidrio puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Coliza marco puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Puerta trasera izquierda',S,6,1.5,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera izquierda superior',S,0,0,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera izquierda inferior',S,0,0,0,'Puerta trasera'),
  _p('Limitador de apertura de puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Manija exterior de puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Moldura de puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Coliza barrevidrio puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Coliza marco puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Espejo retrovisor izquierdo (Manual / Eléctrico)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Zócalo exterior izquierdo',S,8,1,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro trasero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Guardabarro trasero izquierdo',S,4,1,0,'Lateral de Carrocería'),
  _p('Tapa de carga de combustible',N,0,0,0,'Lateral de Carrocería'),
  _p('Portezuela interna de carga de combustible',N,0,0,0,'Lateral de Carrocería'),
  _p('Parante delantero izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Pasarruedas interno estructural delantero izquierdo',S,12,1,0,'Lateral de Carrocería'),
  _p('Pasarruedas interno estructural trasero izquierdo',S,12,1,0,'Lateral de Carrocería')
];
var _B1_Z3=[
  _p('Puerta delantera derecha',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha superior',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha inferior',S,0,0,0,'Puerta delantera'),
  _p('Limitador de apertura de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Coliza barrevidrio puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Coliza marco puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Puerta trasera derecha',S,6,1.5,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera derecha superior',S,0,0,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera derecha inferior',S,0,0,0,'Puerta trasera'),
  _p('Limitador de apertura de puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Manija exterior de puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Moldura de puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Coliza barrevidrio puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Coliza marco puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Espejo retrovisor derecho (Manual / Eléctrico)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Zócalo exterior derecho',S,8,1,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro trasero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Guardabarro trasero derecho',S,12,1,0,'Lateral de Carrocería'),
  _p('Parante delantero derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Pasarruedas interno estructural delantero derecho',S,6,1,0,'Lateral de Carrocería'),
  _p('Pasarruedas interno estructural trasero derecho',S,6,1,0,'Lateral de Carrocería')
];
var _B1_Z4=[
  _p('Paragolpes trasero',S,6,1.5,0,'Paragolpes trasero'),
  _p('Alma metálica de paragolpes trasero',S,8,1,0,'Paragolpes trasero'),
  _p('Absorbedor de impacto de paragolpes trasero',N,0,0,0,'Paragolpes trasero'),
  _p('Soporte de paragolpes trasero izquierdo',N,0,0,0,'Paragolpes trasero'),
  _p('Soporte de paragolpes trasero derecho',N,0,0,0,'Paragolpes trasero'),
  _p('Guía de paragolpes trasero izquierda',N,0,0,0,'Paragolpes trasero'),
  _p('Guía de paragolpes trasero derecha',N,0,0,0,'Paragolpes trasero'),
  _p('Moldurón negro de paragolpes trasero',N,0,0,0,'Paragolpes trasero'),
  _p('Tapa de baúl (Modelos Sedán)',S,6,2.5,0,'Tapa de baúl'),
  _p('Bisagra de tapa o portón trasero izquierda',S,0,0,0,'Tapa de baúl'),
  _p('Bisagra de tapa o portón trasero derecha',S,0,0,0,'Tapa de baúl'),
  _p('Cerradura de baúl / portón trasero',N,0,0,0,'Tapa de baúl'),
  _p('Botón de apertura exterior de baúl',N,0,0,0,'Tapa de baúl'),
  _p('Portón trasero (Modelos Hatchback / SUV)',S,6,2.5,0,'Portón trasero'),
  _p('Amortiguador neumático de portón izquierdo',N,0,0,0,'Portón trasero'),
  _p('Amortiguador neumático de portón derecho',N,0,0,0,'Portón trasero'),
  _p('Spoiler trasero de techo / Deflector trasero',N,0,0,0,'Portón trasero'),
  _p('Faro trasero izquierdo fijo (En carrocería)',N,0,0,0,'Faros traseros'),
  _p('Faro trasero derecho fijo (En carrocería)',N,0,0,0,'Faros traseros'),
  _p('Extensión de faro trasero izquierdo (En tapa / portón)',N,0,0,0,'Faros traseros'),
  _p('Extensión de faro trasero derecho (En tapa / portón)',N,0,0,0,'Faros traseros'),
  _p('Tercer Luz de Stop',N,0,0,0,'Faros traseros'),
  _p('Panel de cola',S,8,1.5,0,'Estructura trasera'),
  _p('Sede de faro trasero izquierdo',S,4,0.5,0,'Estructura trasera'),
  _p('Sede de faro trasero derecho',S,4,0.5,0,'Estructura trasera'),
  _p('Piso de baúl',S,8,2,0,'Estructura trasera'),
  _p('Alojamiento de rueda de auxilio',S,8,1,0,'Estructura trasera'),
  _p('Larguero estructural trasero izquierdo',S,8,0.5,0,'Estructura trasera'),
  _p('Larguero estructural trasero derecho',S,8,0.5,0,'Estructura trasera')
];
var _B1_Z5=[
  // ── Centro / Comunes ──────────────────────────────────
  _p('Cuna de motor (Araña / Subchasis)',S,4,0,6,'Centro / Comunes'),
  _p('Caja de dirección (Hidráulica / Eléctrica)',S,3,0,4,'Centro / Comunes'),
  _p('Barra estabilizadora delantera',N,0.5,0,0,'Centro / Comunes'),
  _p('Pastillas de freno delanteras',N,0.5,0,0,'Centro / Comunes'),
  _p('Líquido hidráulico de dirección',N,0,0,0,'Centro / Comunes'),
  // ── Lado izquierdo ────────────────────────────────────
  _p('Neumático delantero izquierdo',N,0,0,0,'Lado izquierdo'),
  _p('Llanta delantera izquierda',S,0,0,1,'Lado izquierdo'),
  _p('Amortiguador delantero izquierdo',N,1,0,0,'Lado izquierdo'),
  _p('Espiral delantero izquierdo',N,1,0,0,'Lado izquierdo'),
  _p('Cazoleta de amortiguador delantero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Parrilla de suspensión inferior izquierda',N,1.5,0,0,'Lado izquierdo'),
  _p('Rótula de suspensión izquierda',N,0.5,0,0,'Lado izquierdo'),
  _p('Bieleta de barra estabilizadora izquierda',N,0.5,0,0,'Lado izquierdo'),
  _p('Precap (Axial de dirección) izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Extremo de dirección izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Portamaza delantero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Maza de rueda delantera izquierda',N,1,0,0,'Lado izquierdo'),
  _p('Semieje izquierdo completo',S,1.5,0,4,'Lado izquierdo'),
  _p('Rodamiento de rueda delantera izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Disco de freno delantero izquierdo',N,1,0,0,'Lado izquierdo'),
  _p('Caliper delantero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Campana de freno delantera izquierda',N,0.5,0,0,'Lado izquierdo'),
  // ── Lado derecho ──────────────────────────────────────
  _p('Neumático delantero derecho',N,0,0,0,'Lado derecho'),
  _p('Llanta delantera derecha',S,0,0,1,'Lado derecho'),
  _p('Amortiguador delantero derecho',N,1,0,0,'Lado derecho'),
  _p('Espiral delantero derecho',N,1,0,0,'Lado derecho'),
  _p('Cazoleta de amortiguador delantero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Parrilla de suspensión inferior derecha',N,1.5,0,0,'Lado derecho'),
  _p('Rótula de suspensión derecha',N,0.5,0,0,'Lado derecho'),
  _p('Bieleta de barra estabilizadora derecha',N,0.5,0,0,'Lado derecho'),
  _p('Precap (Axial de dirección) derecho',N,0.5,0,0,'Lado derecho'),
  _p('Extremo de dirección derecho',N,0.5,0,0,'Lado derecho'),
  _p('Portamaza delantero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Maza de rueda delantera derecha',N,1,0,0,'Lado derecho'),
  _p('Semieje derecho completo',S,1.5,0,4,'Lado derecho'),
  _p('Rodamiento de rueda delantera derecho',N,0.5,0,0,'Lado derecho'),
  _p('Disco de freno delantero derecho',N,1,0,0,'Lado derecho'),
  _p('Caliper delantero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Campana de freno delantera derecha',N,0.5,0,0,'Lado derecho')
];
var _Z_TREN_TRA_SED=[
  // ── Centro / Comunes ──────────────────────────────────
  _p('Eje trasero',S,4,0,6,'Centro / Comunes'),
  _p('Pastillas de freno traseras',N,0.5,0,0,'Centro / Comunes'),
  // ── Lado izquierdo ────────────────────────────────────
  _p('Neumático trasero izquierdo',N,0,0,0,'Lado izquierdo'),
  _p('Llanta trasera izquierda',S,0,0,1,'Lado izquierdo'),
  _p('Amortiguador trasero izquierdo',N,1,0,0,'Lado izquierdo'),
  _p('Espiral trasero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Punta de eje trasero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Maza de rueda trasera izquierda',N,1,0,0,'Lado izquierdo'),
  _p('Rodamiento trasero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Disco de freno trasero izquierdo',N,1,0,0,'Lado izquierdo'),
  _p('Caliper trasero izquierdo',N,0.5,0,0,'Lado izquierdo'),
  _p('Campana de freno trasera izquierda',N,0.5,0,0,'Lado izquierdo'),
  // ── Lado derecho ──────────────────────────────────────
  _p('Neumático trasero derecho',N,0,0,0,'Lado derecho'),
  _p('Llanta trasera derecha',S,0,0,1,'Lado derecho'),
  _p('Amortiguador trasero derecho',N,1,0,0,'Lado derecho'),
  _p('Espiral trasero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Punta de eje trasero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Maza de rueda trasera derecha',N,1,0,0,'Lado derecho'),
  _p('Rodamiento trasero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Disco de freno trasero derecho',N,1,0,0,'Lado derecho'),
  _p('Caliper trasero derecho',N,0.5,0,0,'Lado derecho'),
  _p('Campana de freno trasera derecha',N,0.5,0,0,'Lado derecho')
];
var _B1_Z6=[
  _p('Block de motor',N,8,0,0,'Componentes de motor'),
  _p('Cárter de aceite',N,1,0,0,'Componentes de motor'),
  _p('Tapa de cilindros',N,3,0,0,'Componentes de motor'),
  _p('Tapa de válvulas',N,1,0,0,'Componentes de motor'),
  _p('Soporte / Pata de motor izquierda',N,1,0,0,'Componentes de motor'),
  _p('Soporte / Pata de motor derecha',N,1,0,0,'Componentes de motor'),
  _p('Soporte / Pata de motor trasera',N,1,0,0,'Componentes de motor'),
  // ── Sistema de admisión de aire ──────────────────────
  _p('Filtro de aire (Elemento)',N,0,0,0,'Sistema de admisión de aire'),
  _p('Carcaza de filtro de aire',N,0.5,0,0,'Sistema de admisión de aire'),
  _p('Toma de aire (Entrada)',N,0,0,0,'Sistema de admisión de aire'),
  // ── Sistema de refrigeración ─────────────────────────
  _p('Radiador de agua de motor',N,1,0,0,'Sistema de refrigeración'),
  _p('Condensador de aire acondicionado',N,1,0,0,'Sistema de refrigeración'),
  _p('Electroventilador completo (Carenado y aspas)',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Depósito de expansión de refrigerante',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Compresor de aire acondicionado',N,1,0,0,'Sistema de refrigeración'),
  _p('Intercooler',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Jgo. Mangueras de intercooler',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Manguera de radiador superior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Manguera de radiador inferior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Caño A/A superior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Caño A/A inferior',N,0.5,0,0,'Sistema de refrigeración'),
  // ── Sistema eléctrico / electrónico ──────────────────
  _p('Batería',N,0,0,0,'Sistema eléctrico / electrónico'),
  _p('Bandeja de sujeción de batería',N,0.5,0,0,'Sistema eléctrico / electrónico'),
  _p('Alternador',N,1,0,0,'Sistema eléctrico / electrónico'),
  _p('Computadora de motor (ECU)',N,0.5,0,0,'Sistema eléctrico / electrónico'),
  _p('Fusiblera del vano motor',N,1,0,0,'Sistema eléctrico / electrónico'),
  _p('Módulo de control ABS / ESP',N,1,0,0,'Sistema eléctrico / electrónico'),
  // ── Sistema de frenos (vano) ──────────────────────────
  _p('Bomba de freno / Servoasistencia (Servofreno)',N,1,0,0,'Sistema de frenos (vano)'),
  _p('Agua desmineralizada',N,0,0,0,'Fluidos'),
  _p('Líquido refrigerante',N,0,0,0,'Fluidos'),
  _p('Aceite de motor',N,0,0,0,'Fluidos'),
  _p('Aceite de caja',N,0,0,0,'Fluidos'),
  _p('Líquido de frenos',N,0,0,0,'Fluidos')
];
var _B1_Z7=[
  _p('Techo',S,8,3,12),
  _p('Refuerzo transversal de techo',S,1,0.5,1),
  _p('Tapizado de techo',N,3),_p('Cristal de techo',N,4),
  _p('Mecanismo de apertura de cristal de techo',S,2,0,4),
  _p('Antena',N,0),_p('Base de antena',N,1.5),
  _p('Moldura de techo derecha',N,0),_p('Moldura de techo izquierda',N,0)
];
var _B1_Z8=[
  // ── Centro / Comunes ──────────────────────────────────
  _p('Parabrisas delantero',N,2),
  _p('Moldura lateral de parabrisas izquierda',N,0),
  _p('Moldura lateral de parabrisas derecha',N,0),
  _p('Rejilla bajo parabrisas',N,0),
  _p('Luneta trasera',N,2),
  // ── Lado izquierdo ────────────────────────────────────
  _p('Cristal de puerta delantera izquierda',N,0.5),
  _p('Mecanismo levantacristal delantero izquierdo',N,1),
  _p('Cristal de puerta trasera izquierda',N,0.5),
  _p('Mecanismo levantacristal trasero izquierdo',N,1),
  _p('Cristal fijo de custodia lateral izquierdo',N,1),
  // ── Lado derecho ──────────────────────────────────────
  _p('Cristal de puerta delantera derecha',N,0.5),
  _p('Mecanismo levantacristal delantero derecho',N,1),
  _p('Cristal de puerta trasera derecha',N,0.5),
  _p('Mecanismo levantacristal trasero derecho',N,1),
  _p('Cristal fijo de custodia lateral derecho',N,1)
];
var _BASE1={'Frontal':_B1_Z1,'Lateral Izquierda':_B1_Z2,'Lateral Derecha':_B1_Z3,'Trasera':_B1_Z4,'Tren Delantero y Tracción':_B1_Z5,'Tren Trasero':_Z_TREN_TRA_SED,'Mecánica / Vano Motor':_B1_Z6,'Techo':_B1_Z7,'Cristales':_B1_Z8,'Seguridad':_Z9_SEG};

var _B2_Z2=[
  _p('Puerta delantera izquierda',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda superior (Reforzada)',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda inferior (Reforzada)',S,0,0,0,'Puerta delantera'),
  _p('Limitador de apertura de puerta delantera izquierda (Extendido)',N,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera izquierda (Larga)',N,0,0,0,'Puerta delantera'),
  _p('Espejo retrovisor izquierdo (Manual / Eléctrico)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Zócalo exterior izquierdo (Largo)',S,8,1,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro trasero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Guardabarro trasero izquierdo (Estructural grande)',S,12,2,0,'Lateral de Carrocería'),
  _p('Parante delantero izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central izquierdo',S,8,0.5,0,'Lateral de Carrocería')
];
var _B2_Z3=[
  _p('Puerta delantera derecha',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha superior (Reforzada)',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha inferior (Reforzada)',S,0,0,0,'Puerta delantera'),
  _p('Limitador de apertura de puerta delantera derecha (Extendido)',N,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera derecha (Larga)',N,0,0,0,'Puerta delantera'),
  _p('Espejo retrovisor derecho (Manual / Eléctrico)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Zócalo exterior derecho (Largo)',S,8,1,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro trasero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Guardabarro trasero derecho (Estructural grande)',S,12,2,0,'Lateral de Carrocería'),
  _p('Parante delantero derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central derecho',S,8,0.5,0,'Lateral de Carrocería')
];
var _B2_Z4=[
  _p('Paragolpes trasero',S,6,1.5,0,'Paragolpes trasero'),
  _p('Alma metálica de paragolpes trasero',S,8,1,0,'Paragolpes trasero'),
  _p('Soporte de paragolpes trasero izquierdo',N,0,0,0,'Paragolpes trasero'),
  _p('Soporte de paragolpes trasero derecho',N,0,0,0,'Paragolpes trasero'),
  _p('Moldurón negro de paragolpes trasero',N,0,0,0,'Paragolpes trasero'),
  _p('Portón trasero corto',S,6,2.5,0,'Portón trasero'),
  _p('Bisagra de portón trasero izquierda',S,0,0,0,'Portón trasero'),
  _p('Bisagra de portón trasero derecha',S,0,0,0,'Portón trasero'),
  _p('Amortiguador neumático de portón izquierdo',N,0,0,0,'Portón trasero'),
  _p('Amortiguador neumático de portón derecho',N,0,0,0,'Portón trasero'),
  _p('Cerradura de portón trasero',N,0,0,0,'Portón trasero'),
  _p('Faro trasero izquierdo fijo',N,0,0,0,'Faros traseros'),_p('Faro trasero derecho fijo',N,0,0,0,'Faros traseros'),
  _p('Tercer Luz de Stop',N,0,0,0,'Faros traseros'),
  _p('Panel de cola',S,8,1.5,0,'Estructura trasera'),
  _p('Piso de baúl',S,8,2,0,'Estructura trasera'),
  _p('Larguero estructural trasero izquierdo',S,8,0.5,0,'Estructura trasera'),
  _p('Larguero estructural trasero derecho',S,8,0.5,0,'Estructura trasera')
];
var _B2_Z8=[
  _p('Parabrisas delantero',N),_p('Luneta trasera',N),
  _p('Cristal de puerta delantera izquierda (Extendido)',N),_p('Cristal de puerta delantera derecha (Extendido)',N),
  _p('Cristal lateral trasero izquierdo (Fijo o pivotante)',N),_p('Cristal lateral trasero derecho (Fijo o pivotante)',N),
  _p('Mecanismo levantacristal delantero izquierdo',N),_p('Mecanismo levantacristal delantero derecho',N)
];
var _BASE2={'Frontal':_B1_Z1,'Lateral Izquierda':_B2_Z2,'Lateral Derecha':_B2_Z3,'Trasera':_B2_Z4,'Tren Delantero y Tracción':_B1_Z5,'Tren Trasero':_Z_TREN_TRA_SED,'Mecánica / Vano Motor':_B1_Z6,'Techo':_B1_Z7,'Cristales':_B2_Z8,'Seguridad':_Z9_SEG};

var _B3_Z1=[
  _p('Paragolpes delantero (Reforzado / Cromado / Plástico)',S,8,1.5,0,'Paragolpes delantero'),
  _p('Alma de paragolpes delantero',S,8,1,0,'Paragolpes delantero'),
  _p('Soporte estructural pesado de paragolpes izquierdo',N,0,0,0,'Paragolpes delantero'),
  _p('Soporte estructural pesado de paragolpes derecho',N,0,0,0,'Paragolpes delantero'),
  _p('Rejilla / Parrilla frontal central (Gran escala)',N,0,0,0,'Paragolpes delantero'),
  _p('Marco de faro auxiliar izquierdo',N,0,0,0,'Paragolpes delantero'),
  _p('Marco de faro auxiliar derecho',N,0,0,0,'Paragolpes delantero'),
  _p('Portapatente delantero',N,0,0,0,'Paragolpes delantero'),
  _p('Faro auxiliar izquierdo (Antiniebla)',N,0,0,0,'Paragolpes delantero'),
  _p('Faro auxiliar derecho (Antiniebla)',N,0,0,0,'Paragolpes delantero'),
  _p('Capot',S,6,4,0,'Capot'),
  _p('Manta aislante de capot',N,0,0,0,'Capot'),
  _p('Bisagra de capot izquierda',S,0,0,0,'Capot'),
  _p('Bisagra de capot derecha',S,0,0,0,'Capot'),
  _p('Cerradura de capot',N,0,0,0,'Capot'),
  _p('Guardabarros delantero izquierdo',S,4,1,0,'GDI + Óptica I + G.Plast I'),
  _p('Óptica principal izquierda',N,0,0,0,'GDI + Óptica I + G.Plast I'),
  _p('Guardaplast izquierdo',N,0,0,0,'GDI + Óptica I + G.Plast I'),
  _p('Guardabarros delantero derecho',S,4,1,0,'GDD + Óptica D + G.Plast D'),
  _p('Óptica principal derecha',N,0,0,0,'GDD + Óptica D + G.Plast D'),
  _p('Guardaplast derecho',N,0,0,0,'GDD + Óptica D + G.Plast D'),
  _p('Máscara plástica',N,0,0,0,'Frente de carrocería'),_p('Travesaño superior de panel frontal',S,4,0.5,0,'Frente de carrocería'),_p('Travesaño inferior de panel frontal',S,4,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero izquierdo',S,16,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero derecho',S,16,0.5,0,'Frente de carrocería')
];
var _B3_Z2=[
  _p('Puerta de cabina izquierda',S,8,1.5,0,'Puerta de cabina'),
  _p('Bisagra de puerta izquierda superior',S,0,0,0,'Puerta de cabina'),
  _p('Bisagra de puerta izquierda inferior',S,0,0,0,'Puerta de cabina'),
  _p('Manija exterior de puerta izquierda',N,0,0,0,'Puerta de cabina'),
  _p('Moldura de puerta delantera izquierda',N,0,0,0,'Puerta de cabina'),
  _p('Espejo retrovisor izquierdo (Brazo extendido)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Zócalo inferior de cabina izquierdo',S,8,1,0,'Lateral de Carrocería'),
  _p('Estribo lateral izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de lateral exterior de caja izquierdo (Overfender / Buchi)',N,0,0,0,'Lateral de Carrocería'),
  _p('Parante delantero izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central izquierdo',S,8,0.5,0,'Lateral de Carrocería')
];
var _B3_Z3=[
  _p('Puerta de cabina derecha',S,8,1.5,0,'Puerta de cabina'),
  _p('Bisagra de puerta derecha superior',S,0,0,0,'Puerta de cabina'),
  _p('Bisagra de puerta derecha inferior',S,0,0,0,'Puerta de cabina'),
  _p('Manija exterior de puerta derecha',N,0,0,0,'Puerta de cabina'),
  _p('Moldura de puerta delantera derecha',N,0,0,0,'Puerta de cabina'),
  _p('Espejo retrovisor derecho (Brazo extendido)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Zócalo inferior de cabina derecho',S,8,1,0,'Lateral de Carrocería'),
  _p('Estribo lateral derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de lateral exterior de caja derecho (Overfender / Buchi)',N,0,0,0,'Lateral de Carrocería'),
  _p('Parante delantero derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central derecho',S,8,0.5,0,'Lateral de Carrocería')
];
var _B3_Z4=[
  _p('Portón trasero de caja de carga (Panel de chapa)',S,6,2,0,'Portón de caja'),
  _p('Manija de apertura de portón trasero',N,0,0,0,'Portón de caja'),
  _p('Bisagra de portón de caja izquierda',S,0,0,0,'Portón de caja'),
  _p('Bisagra de portón de caja derecha',S,0,0,0,'Portón de caja'),
  _p('Cable de retención de portón izquierdo',N,0,0,0,'Portón de caja'),
  _p('Cable de retención de portón derecho',N,0,0,0,'Portón de caja'),
  _p('Paragolpes trasero',S,6,2,0,'Paragolpes trasero'),
  _p('Faro trasero izquierdo',N,0,0,0,'Faros traseros'),
  _p('Faro trasero derecho',N,0,0,0,'Faros traseros'),
  _p('Tercer Luz de Stop',N,0,0,0,'Faros traseros'),
  _p('Barra antivuelco (San Antonio)',N,0,0,0,'Paragolpes trasero'),
  _p('Lona marítima de cobertura de caja',N,0,0,0,'Paragolpes trasero'),
  _p('Cúpula rígida trasera',N,0,0,0,'Paragolpes trasero'),
  _p('Panel de cola de caja de carga',S,6,1.5,0,'Estructura trasera'),
  _p('Piso de carga de chapa',S,12,3,0,'Estructura trasera'),
  _p('Larguero estructural de chasis trasero izquierdo',S,10,0.5,0,'Estructura trasera'),
  _p('Larguero estructural de chasis trasero derecho',S,10,0.5,0,'Estructura trasera'),
  _p('Estructura / Panel interno lateral de caja izquierdo',N,0,0,0,'Estructura trasera'),
  _p('Estructura / Panel interno lateral de caja derecho',N,0,0,0,'Estructura trasera'),
  _p('Pasarruedas interno de caja (Buche interior) izquierdo',S,8,1,0,'Estructura trasera'),
  _p('Pasarruedas interno de caja (Buche interior) derecho',S,8,1,0,'Estructura trasera')
];
var _B3_Z5=[
  _p('Amortiguador delantero reforzado izquierdo',N),_p('Amortiguador delantero reforzado derecho',N),
  _p('Brazo / Parrilla de suspensión superior izquierda',N),_p('Brazo / Parrilla de suspensión superior derecha',N),
  _p('Brazo / Parrilla de suspensión inferior izquierda',N),_p('Brazo / Parrilla de suspensión inferior derecha',N),
  _p('Rótula de suspensión superior izquierda',N),_p('Rótula de suspensión superior derecha',N),
  _p('Barra estabilizadora delantera pesada',N),_p('Caja / Cremallera de dirección asistida pesada',N),
  _p('Extremo de dirección izquierdo',N),_p('Extremo de dirección derecho',N),
  _p('Portamaza reforzado izquierdo',N),_p('Portamaza reforzado derecho',N),
  _p('Diferencial delantero (Bocha delantera)',N),_p('Palier / Semieje delantero izquierdo',N),_p('Palier / Semieje delantero derecho',N),
  _p('Actuador de acople de doble tracción',N),
  _p('Paquete de elásticos traseros izquierdo (Hojas ballesta)',N),_p('Paquete de elásticos traseros derecho (Hojas ballesta)',N),
  _p('Amortiguador trasero izquierdo',N),_p('Amortiguador trasero derecho',N),
  _p('Eje trasero',N),_p('Punta de eje trasero izquierdo',N),_p('Punta de eje trasero derecho',N),
  _p('Maza de rueda trasera izquierda',N),_p('Maza de rueda trasera derecha',N),
  _p('Rodamiento trasero izquierdo',N),_p('Rodamiento trasero derecho',N),
  _p('Diferencial trasero (Bocha trasera)',N),_p('Palier trasero izquierdo',N),_p('Palier trasero derecho',N),
  _p('Disco de freno trasero izquierdo',N),_p('Disco de freno trasero derecho',N),
  _p('Caliper trasero izquierdo',N),_p('Caliper trasero derecho',N),
  _p('Pastillas de freno traseras',N),
  _p('Campana de freno trasera izquierda',N),_p('Campana de freno trasera derecha',N)
];
var _B3_Z6=[
  // ── Componentes de motor ──────────────────────────────
  _p('Block motor',N,8,0,0,'Componentes de motor'),
  _p('Cárter de aceite reforzado',N,1,0,0,'Componentes de motor'),
  _p('Turboalimentador',N,1,0,0,'Componentes de motor'),
  _p('Soporte de motor reforzado izquierdo',N,1,0,0,'Componentes de motor'),
  _p('Soporte de motor reforzado derecho',N,1,0,0,'Componentes de motor'),
  // ── Sistema de admisión de aire ──────────────────────
  _p('Filtro de aire (Elemento)',N,0,0,0,'Sistema de admisión de aire'),
  _p('Carcaza de filtro de aire',N,0.5,0,0,'Sistema de admisión de aire'),
  _p('Toma de aire (Entrada)',N,0,0,0,'Sistema de admisión de aire'),
  // ── Sistema de refrigeración ─────────────────────────
  _p('Radiador de agua pesado',N,1,0,0,'Sistema de refrigeración'),
  _p('Condensador de aire acondicionado',N,1,0,0,'Sistema de refrigeración'),
  _p('Intercooler',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Jgo. Mangueras de intercooler',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Manguera de radiador superior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Manguera de radiador inferior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Caño A/A superior',N,0.5,0,0,'Sistema de refrigeración'),
  _p('Caño A/A inferior',N,0.5,0,0,'Sistema de refrigeración'),
  // ── Transmisión 4x4 ──────────────────────────────────
  _p('Caja de transferencia (Alta / Baja 4x4)',N,1,0,0,'Transmisión 4x4'),
  _p('Cardán delantero completo',N,1,0,0,'Transmisión 4x4'),
  _p('Cardán trasero completo',N,1,0,0,'Transmisión 4x4'),
  // ── Fluidos ───────────────────────────────────────────
  _p('Agua desmineralizada',N,0,0,0,'Fluidos'),
  _p('Líquido refrigerante',N,0,0,0,'Fluidos'),
  _p('Aceite de motor',N,0,0,0,'Fluidos'),
  _p('Aceite de caja',N,0,0,0,'Fluidos'),
  _p('Líquido de frenos',N,0,0,0,'Fluidos')
];
var _B3_Z7=[_p('Panel de chapa de techo de cabina corta',S),_p('Tapizado de techo',N),_p('Antena',N),_p('Base de antena',N)];
var _B3_Z8=[
  _p('Parabrisas delantero',N),_p('Luneta trasera de cabina (Fija o corrediza central)',N),
  _p('Cristal de puerta de cabina izquierda',N),_p('Cristal de puerta de cabina derecha',N),
  _p('Mecanismo levantacristal izquierdo',N),_p('Mecanismo levantacristal derecho',N)
];
var _BASE3={'Frontal':_B3_Z1,'Lateral Izquierda':_B3_Z2,'Lateral Derecha':_B3_Z3,'Trasera / Caja de Carga':_B3_Z4,'Tren Delantero y Tracción 4x4':_B3_Z5,'Mecánica':_B3_Z6,'Techo':_B3_Z7,'Cristales':_B3_Z8,'Seguridad':_Z9_SEG};
// Nota: Pickup cabina simple no tiene Tren Trasero separado (incluido en Tren Delantero y Tracción 4x4)

var _B4_Z2=[
  _p('Puerta delantera izquierda',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda superior',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera izquierda inferior',S,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera izquierda',N,0,0,0,'Puerta delantera'),
  _p('Puerta trasera izquierda',S,6,1.5,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera izquierda superior',S,0,0,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera izquierda inferior',S,0,0,0,'Puerta trasera'),
  _p('Manija exterior de puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Moldura de puerta trasera izquierda',N,0,0,0,'Puerta trasera'),
  _p('Espejo retrovisor izquierdo (Brazo extendido)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor izquierdo',N,0,0,0,'Espejo'),
  _p('Zócalo inferior de cabina doble izquierdo (Largo)',S,8,1,0,'Lateral de Carrocería'),
  _p('Estribo lateral izquierdo (Versión larga)',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero izquierdo',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de lateral exterior de caja izquierdo (Overfender / Buchi)',N,0,0,0,'Lateral de Carrocería'),
  _p('Parante delantero izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central izquierdo',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante C (Trasero de cabina larga) izquierdo',N,0,0,0,'Lateral de Carrocería')
];
var _B4_Z3=[
  _p('Puerta delantera derecha',S,6,1.5,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha superior',S,0,0,0,'Puerta delantera'),
  _p('Bisagra de puerta delantera derecha inferior',S,0,0,0,'Puerta delantera'),
  _p('Manija exterior de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Moldura de puerta delantera derecha',N,0,0,0,'Puerta delantera'),
  _p('Puerta trasera derecha',S,6,1.5,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera derecha superior',S,0,0,0,'Puerta trasera'),
  _p('Bisagra de puerta trasera derecha inferior',S,0,0,0,'Puerta trasera'),
  _p('Manija exterior de puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Moldura de puerta trasera derecha',N,0,0,0,'Puerta trasera'),
  _p('Espejo retrovisor derecho (Brazo extendido)',N,0,0,0,'Espejo'),
  _p('Carcasa de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Cristal de espejo retrovisor derecho',N,0,0,0,'Espejo'),
  _p('Zócalo inferior de cabina doble derecho (Largo)',S,8,1,0,'Lateral de Carrocería'),
  _p('Estribo lateral derecho (Versión larga)',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de guardabarro delantero derecho',N,0,0,0,'Lateral de Carrocería'),
  _p('Moldura de lateral exterior de caja derecho (Overfender / Buchi)',N,0,0,0,'Lateral de Carrocería'),
  _p('Parante delantero derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante central derecho',S,8,0.5,0,'Lateral de Carrocería'),
  _p('Parante C (Trasero de cabina larga) derecho',N,0,0,0,'Lateral de Carrocería')
];
var _B4_Z8=[
  _p('Parabrisas delantero',N),_p('Luneta trasera de cabina (Fija o corrediza)',N),
  _p('Cristal de puerta delantera izquierda',N),_p('Cristal de puerta delantera derecha',N),
  _p('Cristal de puerta trasera izquierda',N),_p('Cristal de puerta trasera derecha',N),
  _p('Mecanismo levantacristal delantero izquierdo',N),_p('Mecanismo levantacristal delantero derecho',N),
  _p('Mecanismo levantacristal trasero izquierdo',N),_p('Mecanismo levantacristal trasero derecho',N)
];
var _BASE4={'Frontal':_B3_Z1,'Lateral Izquierda':_B4_Z2,'Lateral Derecha':_B4_Z3,'Trasera / Caja de Carga':_B3_Z4,'Tren Delantero y Tracción 4x4':_B3_Z5,'Mecánica':_B3_Z6,'Techo':_B3_Z7,'Cristales':_B4_Z8,'Seguridad':_Z9_SEG};

var _BASE5={
  'Frontal':[
    _p('Paragolpes delantero',S,8,1.5,0,'Paragolpes delantero'),
    _p('Alma de paragolpes delantero',S,8,1,0,'Paragolpes delantero'),
    _p('Parrilla frontal central',N,0,0,0,'Paragolpes delantero'),
    _p('Portapatente delantero',N,0,0,0,'Paragolpes delantero'),
    _p('Capot',S,3,3,0,'Capot'),
    _p('Bisagra de capot izquierda',S,0,0,0,'Capot'),
    _p('Bisagra de capot derecha',S,0,0,0,'Capot'),
    _p('Cerradura de capot',N,0,0,0,'Capot'),
    _p('Guardabarros delantero izquierdo',S,4,1,0,'GDI + Óptica I + G.Plast I'),
    _p('Óptica principal izquierda',N,0,0,0,'GDI + Óptica I + G.Plast I'),
    _p('Guardaplast izquierdo',N,0,0,0,'GDI + Óptica I + G.Plast I'),
    _p('Guardabarros delantero derecho',S,4,1,0,'GDD + Óptica D + G.Plast D'),
    _p('Óptica principal derecha',N,0,0,0,'GDD + Óptica D + G.Plast D'),
    _p('Guardaplast derecho',N,0,0,0,'GDD + Óptica D + G.Plast D'),
    _p('Máscara plástica',N,0,0,0,'Frente de carrocería'),_p('Travesaño superior de panel frontal',S,4,0.5,0,'Frente de carrocería'),_p('Travesaño inferior de panel frontal',S,4,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero izquierdo',S,16,0.5,0,'Frente de carrocería'),
  _p('Larguero delantero derecho',S,16,0.5,0,'Frente de carrocería')
  ],
  'Lateral Izquierda':[
    _p('Puerta delantera izquierda',S,8,1.5),
    _p('Bisagra de puerta delantera izquierda superior',S),_p('Bisagra de puerta delantera izquierda inferior',S),
    _p('Manija exterior de puerta delantera izquierda',N),_p('Espejo retrovisor izquierdo (Doble visión / Brazo largo)',N),
    _p('Carcasa de espejo retrovisor izquierdo',N),_p('Cristal de espejo retrovisor izquierdo',N),
    _p('Zócalo inferior izquierdo (Zona delantera)',S,8,1),
    _p('Panel lateral de carga izquierdo (Chapa ciega o estructural)',S,16,3),
    _p('Moldura plástica protectora lateral izquierda (Ancha)',N),_p('Moldura de puerta delantera izquierda',N),
    _p('Moldura de guardabarro delantero izquierdo',N),
    _p('Parante delantero izquierdo',S,8,0.5),_p('Parante central izquierdo',S,8,0.5),
    _p('Parante C (Trasero intermedio) izquierdo',N),_p('Parante D (Estructural trasero) izquierdo',N)
  ],
  'Lateral Derecha':[
    _p('Puerta delantera derecha',S,8,1.5),
    _p('Bisagra de puerta delantera derecha superior',S),_p('Bisagra de puerta delantera derecha inferior',S),
    _p('Manija exterior de puerta delantera derecha',N),_p('Espejo retrovisor derecho (Doble visión / Brazo largo)',N),
    _p('Carcasa de espejo retrovisor derecho',N),_p('Cristal de espejo retrovisor derecho',N),
    _p('Zócalo inferior derecho (Zona delantera)',S,8,1),
    _p('Puerta lateral corrediza de carga (Panel de chapa)',S,6,2),_p('Riel / Guía exterior de puerta corrediza',N),
    _p('Cerradura de puerta lateral corrediza',N),_p('Manija exterior de puerta lateral corrediza',N),
    _p('Panel lateral de carga derecho (Tramo fijo)',S,8,2),_p('Moldura de puerta delantera derecha',N),
    _p('Parante delantero derecho',S,8,0.5),_p('Parante central derecho',S,8,0.5),
    _p('Parante C (Trasero intermedio) derecho',N),_p('Parante D (Estructural trasero) derecho',N)
  ],
  'Trasera / Acceso a Carga':[
    _p('Puerta trasera batiente izquierda',S,6,2,0,'Puertas traseras'),
    _p('Bisagra de puerta batiente izquierda superior',S,0,0,0,'Puertas traseras'),
    _p('Bisagra de puerta batiente izquierda inferior',S,0,0,0,'Puertas traseras'),
    _p('Puerta trasera batiente derecha',S,6,2,0,'Puertas traseras'),
    _p('Bisagra de puerta batiente derecha superior',S,0,0,0,'Puertas traseras'),
    _p('Bisagra de puerta batiente derecha inferior',S,0,0,0,'Puertas traseras'),
    _p('Cerradura exterior de puerta trasera batiente',N,0,0,0,'Puertas traseras'),
    _p('Manija exterior de puerta trasera batiente',N,0,0,0,'Puertas traseras'),
    _p('Paragolpes trasero',S,6,2,0,'Paragolpes trasero'),
    _p('Faro trasero vertical izquierdo',N,0,0,0,'Faros traseros'),
    _p('Faro trasero vertical derecho',N,0,0,0,'Faros traseros'),
    _p('Tercer Luz de Stop',N,0,0,0,'Faros traseros'),
    _p('Panel de cola',S,8,1.5),
    _p('Piso de carga de chapa acanalada',S,16,3),
    _p('Larguero estructural de chasis trasero izquierdo',S,16,0.5),_p('Larguero estructural de chasis trasero derecho',S,16,0.5),
    _p('Tabique / Mampara de separación de cabina (Estructural interno)',N)
  ],
  'Tren Delantero y Suspensión':[
    _p('Falso chasis / Subchasis / Cuna de motor reforzada',N),
    _p('Amortiguador delantero reforzado izquierdo',N),_p('Amortiguador delantero reforzado derecho',N),
    _p('Parrilla de suspensión inferior izquierda',N),_p('Parrilla de suspensión inferior derecha',N),
    _p('Rótula de suspensión reforzada izquierda',N),_p('Rótula de suspensión reforzada derecha',N),
    _p('Barra estabilizadora delantera de gran diámetro',N),_p('Caja / Cremallera de dirección asistida reforzada',N),
    _p('Extremo de dirección izquierdo',N),_p('Extremo de dirección derecho',N),
    _p('Semieje pesado izquierdo',N),_p('Semieje pesado derecho',N),
    _p('Eje rígido trasero de carga / Tubo de torsión',N),
    _p('Paquete de elásticos traseros izquierdo',N),_p('Paquete de elásticos traseros derecho',N)
  ],
  'Mecánica':[
    _p('Block motor',N,0,0,0,'Componentes de motor'),
    _p('Soporte de motor reforzado izquierdo',N,0,0,0,'Componentes de motor'),
    _p('Soporte de motor reforzado derecho',N,0,0,0,'Componentes de motor'),
    _p('Radiador de agua compacto',N,0,0,0,'Sistema de refrigeración'),
    _p('Condensador de aire acondicionado',N,0,0,0,'Sistema de refrigeración'),
    _p('Intercooler',N,0,0,0,'Sistema de refrigeración'),
    _p('Jgo. Mangueras de intercooler',N,0,0,0,'Sistema de refrigeración'),
    _p('Manguera de radiador superior',N,0,0,0,'Sistema de refrigeración'),
    _p('Manguera de radiador inferior',N,0,0,0,'Sistema de refrigeración'),
    _p('Caño A/A superior',N,0,0,0,'Sistema de refrigeración'),
    _p('Caño A/A inferior',N,0,0,0,'Sistema de refrigeración'),
    _p('Electroventilador de alta eficiencia',N,0,0,0,'Sistema de refrigeración'),
    _p('Alternador de alta capacidad',N,0,0,0,'Sistema eléctrico / electrónico')
  ],
  'Techo':[_p('Techo',S,16,3)],
  'Cristales':[
    _p('Parabrisas delantero',N,2),
    _p('Luneta trasera (En puertas batientes)',N,2),
    _p('Cristal de puerta delantera izquierda',N,0.5),
    _p('Mecanismo levantacristal delantero izquierdo',N,1),
    _p('Cristal de puerta delantera derecha',N,0.5),
    _p('Mecanismo levantacristal delantero derecho',N,1),
    _p('Cristal de ventana lateral fija izquierda',N,1),
    _p('Cristal de ventana lateral fija derecha',N,1)
  ],
  'Seguridad':_Z9_SEG
};

// ── Motovehiculo ──
var _BASE_MOTO={
  'Parte Delantera':[
    _p('Guardabarro delantero',S,0.5,0.5,0,'Carenado'),
    _p('Máscara frontal',S,1,0.5,0,'Carenado'),
    _p('Cúpula / Parabrisas',N,0.5,0,0,'Carenado'),
    _p('Visera superior',N,0.5,0,0,'Carenado'),
    _p('Cubre horquilla izquierdo',S,0.5,0.5,0,'Carenado'),
    _p('Cubre horquilla derecho',S,0.5,0.5,0,'Carenado'),
    _p('Cacha frontal izquierda',S,0.5,0.5,0,'Carenado'),
    _p('Cacha frontal derecha',S,0.5,0.5,0,'Carenado'),
    _p('Embellecedor frontal',S,0.5,0.5,0,'Carenado'),
    _p('Cristos superior',N,1,0,0,'Carenado'),
    _p('Cristos inferior',N,1,0,0,'Carenado'),
    _p('Araña de carenado',N,0.5,0,0,'Carenado'),
    _p('Faro delantero',N,0.5,0,0,'Óptica delantera'),
    _p('Faro principal',N,0.5,0,0,'Óptica delantera'),
    _p('Faro auxiliar izquierdo',N,0.5,0,0,'Óptica delantera'),
    _p('Faro auxiliar derecho',N,0.5,0,0,'Óptica delantera'),
    _p('LED diurno / DRL',N,0.5,0,0,'Óptica delantera'),
    _p('Luz de posición',N,0.5,0,0,'Óptica delantera'),
    _p('Giro delantero izquierdo',N,0.5,0,0,'Óptica delantera'),
    _p('Giro delantero derecho',N,0.5,0,0,'Óptica delantera'),
    _p('Soporte de faro',N,0.5,0,0,'Óptica delantera'),
    _p('Barral izquierdo',N,1,0,0,'Tren delantero'),
    _p('Barral derecho',N,1,0,0,'Tren delantero'),
    _p('Llanta delantera',N,0.5,0,0,'Tren delantero'),
    _p('Cubierta delantera',N,0.5,0,0,'Tren delantero'),
    _p('Disco de freno delantero',N,0.5,0,0,'Tren delantero'),
    _p('Eje delantero',N,0.5,0,0,'Tren delantero'),
    _p('Caliper delantero',N,0.5,0,0,'Tren delantero'),
    _p('Soporte de caliper',N,0.5,0,0,'Tren delantero'),
    _p('Sensor ABS',N,0.5,0,0,'Tren delantero'),
    _p('Corona ABS',N,0.5,0,0,'Tren delantero'),
    _p('Rulemanes delanteros',N,0.5,0,0,'Tren delantero'),
    _p('Bomba de freno',N,0.5,0,0,'Tren delantero'),
    _p('Depósito líquido de freno',N,0.5,0,0,'Tren delantero'),
    _p('Manguera de freno',N,0.5,0,0,'Tren delantero'),
    _p('Flexible de freno',N,0.5,0,0,'Tren delantero'),
    _p('Manubrio',N,0.5,0,0,'Manubrio y controles'),
    _p('Tablero',N,1,0,0,'Manubrio y controles'),
    _p('Llave de contacto',N,0.5,0,0,'Manubrio y controles'),
    _p('Traba de dirección',N,0.5,0,0,'Manubrio y controles'),
    _p('Espejo izquierdo',N,0.5,0,0,'Manubrio y controles'),
    _p('Espejo derecho',N,0.5,0,0,'Manubrio y controles'),
    _p('Manija de embrague',N,0.5,0,0,'Manubrio y controles'),
    _p('Manija de freno',N,0.5,0,0,'Manubrio y controles'),
    _p('Comando izquierdo',N,0.5,0,0,'Manubrio y controles'),
    _p('Comando derecho',N,0.5,0,0,'Manubrio y controles'),
    _p('Soporte de tablero',N,0.5,0,0,'Manubrio y controles'),
    _p('Cubierta de tablero',N,0.5,0,0,'Manubrio y controles'),
    _p('Chasis delantero',N,0.5,0,0,'Estructura delantera'),
    _p('Soporte frontal',N,0.5,0,0,'Estructura delantera'),
    _p('Tanque de combustible',S,2,1,8,'Tanque'),
    _p('Embellecedor de tanque izquierdo',S,0.5,0.5,0,'Tanque'),
    _p('Embellecedor de tanque derecho',S,0.5,0.5,0,'Tanque')
  ],
  'Lateral Izquierda':[
    _p('Cacha lateral izquierda',S,0.5,0,0,'Lateral izquierdo'),
    _p('Cacha lateral izquierda superior',S,0.5,0,0,'Lateral izquierdo'),
    _p('Cacha lateral izquierda inferior',S,0.5,0,0,'Lateral izquierdo'),
    _p('Embellecedor izquierdo',S,0.5,0,0,'Lateral izquierdo'),
    _p('Protector lateral izquierdo',N,0.5,0,0,'Lateral izquierdo'),
    _p('Gráfica / Calcomanía izquierda',N,0.5,0,0,'Lateral izquierdo'),
    _p('Pedal de cambio',N,0.5,0,0,'Controles izquierdo'),
    _p('Posa pié izquierdo',N,0.5,0,0,'Controles izquierdo'),
    _p('Varillaje de cambios',N,0.5,0,0,'Controles izquierdo'),
    _p('Posa pié conductor izquierdo',N,0.5,0,0,'Controles izquierdo'),
    _p('Posa pié acompañante izquierdo',N,0.5,0,0,'Controles izquierdo'),
    _p('Soporte acompañante izquierdo',N,0.5,0,0,'Controles izquierdo'),
    _p('Contrapeso izquierdo',N,0.5,0,0,'Controles izquierdo'),
    _p('Tapa izquierda de motor',N,0.5,0,0,'Motor izquierdo'),
    _p('Tapa magneto',N,0.5,0,0,'Motor izquierdo'),
    _p('Palanca de arranque',N,0.5,0,0,'Motor izquierdo'),
    _p('Protector motor izquierdo',N,0.5,0,0,'Motor izquierdo'),
  ],
  'Lateral Derecha':[
    _p('Cacha lateral derecha',S,0.5,0,0,'Lateral derecho'),
    _p('Cacha lateral derecha superior',S,0.5,0,0,'Lateral derecho'),
    _p('Cacha lateral derecha inferior',S,0.5,0,0,'Lateral derecho'),
    _p('Embellecedor derecho',S,0.5,0,0,'Lateral derecho'),
    _p('Protector lateral derecho',N,0.5,0,0,'Lateral derecho'),
    _p('Gráfica / Calcomanía derecha',N,0.5,0,0,'Lateral derecho'),
    _p('Escape',N,0.5,0,0,'Controles derecho'),
    _p('Cubre escape',N,0.5,0,0,'Controles derecho'),
    _p('Soporte escape',N,0.5,0,0,'Controles derecho'),
    _p('Pedal de freno',N,0.5,0,0,'Controles derecho'),
    _p('Posa pié derecho',N,0.5,0,0,'Controles derecho'),
    _p('Varilla de freno',N,0.5,0,0,'Controles derecho'),
    _p('Bomba de freno trasera',N,0.5,0,0,'Controles derecho'),
    _p('Depósito líquido de freno trasero',N,0.5,0,0,'Controles derecho'),
    _p('Manguera de freno trasero',N,0.5,0,0,'Controles derecho'),
    _p('Posa pié acompañante derecho',N,0.5,0,0,'Controles derecho'),
    _p('Soporte acompañante derecho',N,0.5,0,0,'Controles derecho'),
    _p('Tapa derecha de motor',N,0.5,0,0,'Motor derecho'),
    _p('Tapa embrague',N,0.5,0,0,'Motor derecho'),
    _p('Protector motor derecho',N,0.5,0,0,'Motor derecho'),
  ],
  'Parte Trasera':[
    _p('Guardabarro trasero',N,1,0,0,'Mecánica trasera'),
    _p('Llanta trasera',N,0.5,0,0,'Mecánica trasera'),
    _p('Cubierta trasera',N,0.5,0,0,'Mecánica trasera'),
    _p('Amortiguador izquierdo',N,0.5,0,0,'Mecánica trasera'),
    _p('Amortiguador derecho',N,0.5,0,0,'Mecánica trasera'),
    _p('Basculante (Tren trasero)',N,3,0,0,'Mecánica trasera'),
    _p('Rulemanes traseros',N,0.5,0,0,'Mecánica trasera'),
    _p('Eje trasero',N,0.5,0,0,'Mecánica trasera'),
    _p('Sistema monoshock',N,1,0,0,'Mecánica trasera'),
    _p('Bieletas',N,0.5,0,0,'Mecánica trasera'),
    _p('Faro trasero',N,0.5,0,0,'Óptica trasera'),
    _p('Luz de freno',N,0.5,0,0,'Óptica trasera'),
    _p('Giro trasero izquierdo',N,0.5,0,0,'Óptica trasera'),
    _p('Giro trasero derecho',N,0.5,0,0,'Óptica trasera'),
    _p('Luz de patente',N,0.5,0,0,'Óptica trasera'),
    _p('Soporte faro trasero',N,0.5,0,0,'Óptica trasera'),
    _p('Colín',N,1,0,0,'Carrocería trasera'),
    _p('Cacha de cola izquierda',S,0.5,0,0,'Carrocería trasera'),
    _p('Cacha de cola derecha',S,0.5,0,0,'Carrocería trasera'),
    _p('Portapatente',N,0.5,0,0,'Carrocería trasera'),
    _p('Portaobjetos',N,0.5,0,0,'Carrocería trasera'),
    _p('Asiento conductor',N,1,0,0,'Habitáculo'),
    _p('Asiento acompañante',N,0.5,0,0,'Habitáculo'),
    _p('Cerradura de asiento',N,0.5,0,0,'Habitáculo'),
    _p('Parrilla trasera',N,0.5,0,0,'Habitáculo'),
    _p('Manija acompañante izquierda',N,0.5,0,0,'Habitáculo'),
    _p('Manija acompañante derecha',N,0.5,0,0,'Habitáculo'),
    _p('Subchasis trasero',N,4,0,0,'Estructura trasera'),
    _p('Soporte guardabarro',N,0.5,0,0,'Estructura trasera'),
  ],
  'Chasis':[
    _p('Chasis principal',S,4,1,8,'Chasis'),
    _p('Subchasis',S,4,1,6,'Chasis'),
    _p('Basculante',S,3,0.5,5,'Chasis'),
    _p('Soportes de motor',N,1,0,0,'Chasis'),
    _p('Soportes de escape',N,0.5,0,0,'Chasis'),
    _p('Soportes de carenado',N,0.5,0,0,'Chasis'),
    _p('Araña frontal',S,3,1,0,'Chasis'),
  ],
};

window.CALC_DATA_GRID={
  'Sedán / Hatchback (4-5 Puertas)':_BASE1,
  'Sedan 4/5 puertas':_BASE1,
  'Sedán / Hatchback (3 Puertas)':_BASE2,
  'Sedan 3 puertas':_BASE2,
  'SUV / Weekend':_BASE3,
  'SUV/Weekend':_BASE3,
  'Utilitario / Furgón':_BASE5,
  'Utilitario':_BASE5,
  'Pickup A Cabina Simple':_BASE3,
  'PickUp-A cabina simple':_BASE3,
  'Pickup B Cabina Simple':_BASE3,
  'PickUp-B cabina simple':_BASE3,
  'Pickup A Cabina Doble':_BASE4,
  'PickUp-A cabina doble':_BASE4,
  'Pickup B Cabina Doble':_BASE4,
  'PickUp-B cabina doble':_BASE4,
  'Motovehiculo':_BASE_MOTO
};
})();
